# docker-compose.elasticsearch.yml
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      # Single-node pour benchmark local
      - discovery.type=single-node

      # Bench "simple" : pas de TLS/auth (à réserver aux tests locaux)
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false

      # RAM (à ajuster selon notre machine)
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://127.0.0.1:9200 >/dev/null || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
